### ISSUE TITLE
Add touhou cursor pack

### ISSUE THREAD

**Issue by 2husecondary** [meanvoid/nixos-overlay#1]
https://moriyashrine.org/files/file/331-touhou-animated-cursor-pack/
these wacky ones

**Comment by ashuramaruzxc** [comment]
Done
Commit 7621783f152730652ddf9f289c63d151fc202348
[`pkgs/cursors/anime-cursors/default.nix`](https://github.com/meanvoid/nixos-overlay/commit/7621783f152730652ddf9f289c63d151fc202348#diff-0bb7787695ece18659726e34b40d623ab230f95c10c6b1ec80a9ceeb9a7ddfc8)
Closing an issue as done
